Домашнее задание 6.13
Windostre/purple_HTML_CSS pull request #1
Opened 2024-02-18 19:50 UTC by Windostre

1.  выполнен перенос контента со страницы блог в html с учетом семантики;
2. выполнена верстка на HTML формы регистрации

2024-02-18 21:05 UTC, GitEsense requested changes
В целом всё хорошо, но есть вопросы, оставлены в комментариях, вносим правки и на повторное ревью

2024-02-18 21:05 UTC, GitEsense commented on 1-Blog/index.html
> +    <title>HTML и CSS с наставником</title>
Можно почитать дополнительно (об этом речи не шло в уроках) про указание мета-тегов (например:
```
<meta name="description" content="PurpleSchool HTML + CSS course">
<meta name="author" content="my_name" />
```

2024-02-18 21:05 UTC, GitEsense commented on 1-Blog/index.html
> +            <li><a href="#">Мой блог</a></li>
Ссылку логотип можно объединить и вынести за навигацию (это относится к логотипу, а не навигации, так будет вернее), например
```
<a href="#"><span>В</span>Мой блог</a>
```

2024-02-18 21:05 UTC, GitEsense commented on 1-Blog/index.html
> +        </div>
текст "Поиск" внести как атрибут placeholder к инпуту

2024-02-18 21:05 UTC, GitEsense commented on 1-Blog/index.html
> +        </h4>
А почему используется тег h2 ? Семантически верно было бы использовать h1, по иерархии всегда идёт h1, за ним H2, то же касается и H4 (тут лучше воспользоваться блочным элементом параграф ("p" - тегом) и лучше будет оформить в виде
```
<div>
   <p>Наталья Васильева</p>
   <p>Разработчик</p>
</div>
```
так будет легче управлять блоком и в перспективе позиционировать

2024-02-18 21:05 UTC, GitEsense commented on 1-Blog/index.html
> +        </section>
Интересно решение, почему один параграф обёрнут в article (семантически говорящий, что может где-то использоваться на другой странице или вынесено в другое место), но всё обёрнуто в section (нераздельный блок). получается, что контент не раздельный, но его часть может быть где-то ещё ?

Имеет право на жизнь, но интересно само решение и почему именно так?

Как насчёт формата:
```
article
   section
      p
      p
      p
   /section
/article
```

2024-02-18 21:05 UTC, GitEsense commented on 2-Form/index.html
> +        </div>
Лучше перенести в форму, т.к. это по сути часть формы и позиционироваться будет вместе, в противном случае выставлять потом будет сложно, да и придётся форму оборачивать с данным блоком в единую обёртку

Так что лучше перенести в форму как "заголовок", можно и не оборачивать, а можно обернуть как "headling", а input'ы формы как "fields"

2024-02-20 11:39 UTC, Windostre commented on 1-Blog/index.html
> +    <title>HTML и CSS с наставником</title>
Спасибо. Поправила во всех файлах

2024-02-20 11:43 UTC, Windostre commented on 1-Blog/index.html
> +            <li><a href="#">Мой блог</a></li>
поправила

2024-02-20 11:45 UTC, Windostre commented on 1-Blog/index.html
> +        </div>
поправила

2024-02-20 11:48 UTC, Windostre commented on 1-Blog/index.html
> +        </h4>
поправила

2024-02-20 11:52 UTC, Windostre commented on 1-Blog/index.html
> +        </section>
Да спасибо! Здесь просто перепутала иерархию section и article.  Использовать article  мне показалось более правильным с точки зрения документации

2024-02-20 12:11 UTC, Windostre commented on 2-Form/index.html
> +        </div>
Поправила (надеюсь правильно поняла). headling - такой тег не нашла, вместо него использовала hgroup.
input` ы завернула в fieldset

2024-02-21 08:58 UTC, GitEsense approved these changes
Всё отлично, можно мерджить )

2024-02-21 08:58 UTC, GitEsense commented on 1-Blog/index.html
> +    </div>
Тут можно и без обёртки в виде div сделать (просто ссылку) - но можно и так)

2024-02-21 09:03 UTC, merged